name: Create cloudinit seed
on:
  push:
    paths:
      - 'cloudinit/**'
    branches:
      - main
permissions:
  contents: write
jobs:
  build_cloudseed:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y cloud-image-utils
    - uses: actions/checkout@v3
    - name: Build cloudinit seed
      run: cloud-localds -v cloudseed.iso ./cloudinit/user-data
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a github release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: "cloudseed.iso"

